### ISSUE TITLE
Turn starcounter-debug-aid into a browser extension

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-debug-aid#51]
Consider turning `starcounter-debug-aid` into a Dev Tools extension. 

1. Can it be made to work in Chrome, Firefox, Edge and Safari?
2. Can it be based on some existing React or Vue.js tool?

**Comment by warpech** [comment]
https://github.com/facebook/react-devtools is quite neat as it works as a real browser extension in Chrome and Firefox (using the [DevTools Extensions API](https://developer.chrome.com/extensions/devtools)). For other browsers (such as Edge, mobile browsers, React Native), it can be used as a React component.

**Comment by alshakero** [comment]
We decided to make it a regular Chrome extension. As opposed to a devTool extension. Much easier to develop and offers the same benefit.

**Comment by warpech** [comment]
More explicitly, the identified benefits are:

- `starcounter-debug-aid` will not have to open on hardcoded keyboard shortcut (CTRL+E). Use the browser toolbar icon instead
- page load size will no longer be affected by `starcounter-debug-aid`
- time to ship new features will not be dependent on Starcounter's release cycle
- Chrome and Firefox extension marketplaces offer automatic updates for the extensions

**Comment by alshakero** [comment]
This is almost done. I spent good 11 hours on it. There will be two options. 
- Open overlay, just like now.
- Open in a popup, to use the app and watch things happen in `sc-debug-aid` at the same time.

It's a Vue app now that is bundled with its CSS and everything. Super maintainable and you can install any NPM package, require it and use it without hassle to add feaures.

**Comment by Mihaiii** [comment]
`It's a Vue app now that is bundled with its CSS and everything. Super maintainable and you can install any NPM package, require it and use it without hassle to add feaures.`

OMG, this is awesome!

**Comment by alshakero** [comment]
This is done here, please test in your favorite browser(s) using these steps:

https://github.com/Starcounter/starcounter-debug-aid/tree/extension#adding-to-browser

**Comment by warpech** [comment]
Amazing icon! :D 

I noticed two problems in Chrome:

1. the red and green arrows on the patch screen are corrupt
2. the patch content is `null` for HTTP patches

![2017-11-21_21-09-25](https://user-images.githubusercontent.com/566463/33094472-98133aa2-cf00-11e7-8b8a-2a7c42354acc.png)

**Comment by alshakero** [comment]
Oh I made a design mistake. I'm killing the app when it's closed. So I can't record patches this way. I'll leave it hidden.

**Comment by thebrauer** [comment]
Nice! I like that I now can have it as a separate popup!

I have noticed two things however. 

1. The arrows next to the expandable levels in the tree are not visible for me:
![image](https://user-images.githubusercontent.com/18281120/33122798-88f62548-cf78-11e7-975e-9d02a1b09e11.png)

2. There seems to be some form of keep-alive ping that is sent from the client every minute. That collapses the tree. Video: https://www.screencast.com/t/usoNChaCpYdy

**Comment by alshakero** [comment]
> the patch content is null for HTTP patches

It is indeed null, here is the original:

![image](https://user-images.githubusercontent.com/17054134/33125520-0e25efa2-cf81-11e7-8cc4-3c66c7475dfb.png)

**Comment by alshakero** [comment]
Should be much better now!

**Comment by alshakero** [comment]
@thebrauer sorry, I didn't see your comment. The first point is solved. I'll check the second. But can you clone again? I changed A LOT.

**Comment by thebrauer** [comment]
@alshakero I took the latest version and it looks much better! The collapsing still occurs however. When I navigate or change things in the GUI I understand if the tree has to be reloaded but its quite annoying that it collapses while I'm navigating the tree because of that keep-alive ping (or whatever that empty array is in the patches)

**Comment by alshakero** [comment]
@thebrauer this is fixed now :)

**Comment by Mihaiii** [comment]
Nice icon :)
Tried it today on Chrome 62.0.3202.94 and I stumbled upon this problem (page freezes):

![chrext1](https://user-images.githubusercontent.com/8951553/33222539-48609d42-d158-11e7-9248-17607e759153.gif)

Might be only my case, I don't know.

**Comment by Mihaiii** [comment]
I also found confusing the `row.url` link on patches' URL column.

**Comment by Mihaiii** [comment]
Ok, since I started with this:
On view-model tab, under tree menu, the properties can be changed, but they should be read only, I think.
Also there, undo/redo buttons don't seem to work or I'm doing it wrong.

**Comment by alshakero** [comment]
Thanks a lot Mihaii! You helped me a lot, I fixed all your concerns. The undo was there by mistake. 

I'll close this issue for now. Just released 0.0.3, update should reach you in minutes.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/DevTools/releases/tag/3.0.0
- announced on the Starcounter blog https://starcounter.io/starcounter-devtools-extension/
